---
- name: Install PostgreSQL
  become: true
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      - acl
    state: latest
    cache_valid_time: 3600

- name: Create the data directory
  file:
    path: "{{ pg_data_directory }}"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
    mode: '0700'
    state: directory
  become: true

- name: Initialize the PostgreSQL database
  command: "sudo -u {{ pg_user }} /usr/lib/postgresql/{{ pg_version }}/bin/initdb -D {{ pg_data_directory }}"
  args:
    creates: "{{ pg_data_directory }}/PG_VERSION"

- name: Configure PostgreSQL to use the new data directory
  lineinfile:
    path: /etc/postgresql/{{ pg_version }}/main/postgresql.conf
    regexp: '^#?data_directory ='
    line: "data_directory = '{{ pg_data_directory }}'"
  become: true

- name: Ensure PostgreSQL service is running
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create database
  postgresql_db:
    state: present
    name: "{{ item }}"
  become_user: postgres
  become: true
  with_items: "{{ postgres_databases }}"

- name: Create PostgreSQL User
  postgresql_user:
    db: postgres
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.role }}"
  with_items: "{{ postgres_users }}"
  become_user: postgres
  become: true
