---
- name: Install PostgreSQL
  become: true
  timeout: 600
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      - acl
    state: latest
    cache_valid_time: 3600

- name: Ensure PostgreSQL service is running
  become: true
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create database
  postgresql_db:
    state: present
    name: "{{ item }}"
  become_user: postgres
  become: true
  with_items: "{{ postgres_databases }}"

- name: Create PostgreSQL User
  postgresql_user:
    db: postgres
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.role }}"
  with_items: "{{ postgres_users }}"
  become_user: postgres
  become: true
