---
- name: Install PostgreSQL
  become: true
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
      - python3-psycopg2
      - acl
    state: latest
    cache_valid_time: 3600

- name: Create the data directory
  ansible.builtin.file:
    path: "{{ postgres_data_directory }}"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_user }}"
    mode: "0700"
    state: directory
  become: true

- name: Initialize the PostgreSQL database
  ansible.builtin.command: sudo -u {{ postgres_user }} /usr/lib/postgresql/{{ postgres_version }}/bin/initdb -D {{ postgres_data_directory }}
  args:
    creates: "{{ postgres_data_directory }}/PG_VERSION"
  become: true

- name: Configure PostgreSQL to use the new data directory
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
    regexp: ^#?data_directory =
    line: data_directory = '{{ postgres_data_directory }}'
  become: true

- name: Ensure PostgreSQL service is running
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Create database
  postgresql_db:
    state: present
    name: "{{ item }}"
  become_user: postgres
  become: true
  with_items: "{{ postgres_databases }}"

- name: Create PostgreSQL User
  postgresql_user:
    db: postgres
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    role_attr_flags: "{{ item.role }}"
  with_items: "{{ postgres_users }}"
  become_user: postgres
  become: true
