---

- name: Remove existing Redis keyring file
  file:
    path: /usr/share/keyrings/redis-archive-keyring.gpg
    state: absent
  become: true

- name: Add Redis GPG Key
  shell: curl -fsSL https://packages.redis.io/gpg | sudo gpg --batch --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
  become: true

- name: Add Redis APT Repository
  shell: echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
  become: true

- name: Ensure Redis data directory exists
  ansible.builtin.file:
    path: "{{ redis_data_directory }}"
    state: directory
    owner: redis
    group: redis
    mode: '0755'
  become: true

- name: Install redis
  apt:
    name: redis
    state: present
    update_cache: yes
  become: true

- name: Ensure Redis is started
  service: name=redis-server state=started enabled=yes
  become: true

- name: Ensure Redis Configuration
  template: src=templates/redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0644
  become: true
  notify: Restart services redis
