---
- name: Add Redis PPA
  ansible.builtin.apt_repository:
    repo: "ppa:redislabs/redis"
    state: present
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install specific Redis version
  ansible.builtin.apt:
    name: "redis-server=7.2*"
    state: present
  become: true

- name: Ensure Redis is started
  service: name=redis-server state=started enabled=yes
  become: true

- name: Ensure Redis Configuration
  template: src=templates/redis.conf.j2 dest=/etc/redis/redis.conf owner=root group=root mode=0644
  become: true
  notify: Restart services redis
