---
- name: Remove existing Redis keyring file
  ansible.builtin.file:
    path: /usr/share/keyrings/redis-archive-keyring.gpg
    state: absent
  become: true

- name: Add Redis GPG Key
  ansible.builtin.shell: |
    # See: https://ansible.readthedocs.io/projects/lint/rules/risky-shell-pipe/#correct-code
    set -o pipefail
    curl -fsSL https://packages.redis.io/gpg | sudo gpg --batch --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
  become: true

- name: Add Redis APT Repository
  ansible.builtin.shell: |
    # See: https://ansible.readthedocs.io/projects/lint/rules/risky-shell-pipe/#correct-code
    set -o pipefail
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
  become: true

- name: Ensure Redis data directory exists
  ansible.builtin.file:
    path: "{{ redis_data_directory }}"
    state: directory
    owner: redis
    group: redis
    mode: "0755"
  become: true

- name: Install redis
  ansible.builtin.apt:
    name: redis
    state: present
    update_cache: true
  become: true

- name: Copy the redis systemd service file
  become: true
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Redis
      After=syslog.target

      [Service]
      ExecStart=/usr/bin/redis-server /etc/redis/redis.conf
      RestartSec=5s
      Restart=on-success

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/redis.service
    owner: root
    group: root
    mode: "0644"
  register: _redis_service

- name: Ensure Redis Configuration
  ansible.builtin.template:
    src: templates/redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: "0644"
    cmd: ""
  become: true
  notify: Restart services redis

- name: Ensure Redis is started
  ansible.builtin.service:
    name: redis
    state: started
    enabled: "yes"
    cmd: ""
  become: true
