---
- name: Install ldap client packages
  become: true
  ansible.builtin.apt:
    name:
      - libpam-ldapd
      - nscd
    state: latest
    cache_valid_time: 3600

- name: LDAP Authentication | Create Home Directories on login
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/common-account
    regexp: pam_mkhomedir\.so
    line: session required pam_mkhomedir.so skel=/etc/skel/ umask=0022
    state: present
  notify: Restart services ldap

- name: LDAP Authentication | Query ldap in nsswitch.conf
  become: true
  ansible.builtin.replace:
    dest: /etc/nsswitch.conf
    regexp: ^({{ item }}(?!.*\bldap\b).*)$
    replace: \1 ldap
    backup: "yes"
  with_items:
    - passwd
    - shadow
    - group
  notify: Restart services ldap

- name: LDAP Authentication | no cache for ldap in nscd.conf
  become: true
  ansible.builtin.replace:
    dest: /etc/nscd.conf
    regexp: ^(\s+enable-cache\s+{{ item }})\s+yes\s*$
    replace: \1 no
    backup: "yes"
  with_items:
    - passwd
    - group
  notify: Restart services ldap

- name: LDAP Authentication | Configure /etc/nslcd.conf
  become: true
  ansible.builtin.template:
    src: nslcd.conf.j2
    dest: /etc/nslcd.conf
    mode: "0600"
  notify: Restart services ldap
