---
- name: Install openldap
  ansible.builtin.include_tasks: openldap.yaml
  when: openldap_server_enabled

- name: Install openldap client
  ansible.builtin.include_tasks: client.yaml
  when: openldap_client_enabled
