---
- name: Check that the conda binary exists
  ansible.builtin.stat:
    path: "{{ miniforge_home }}/bin/mamba"
  register: stat_conda

- name: Download miniconda mambaforge installer
  ansible.builtin.get_url:
    url: https://github.com/conda-forge/miniforge/releases/download/{{ miniforge_version }}/Mambaforge-{{ miniforge_version }}-Linux-x86_64.sh
    checksum: sha256:{{ miniforge_sha256 }}
    dest: /tmp/miniforge.sh
    force: false
    mode: "0755"
  when: not stat_conda.stat.exists

- name: Install miniforge
  become: true
  ansible.builtin.shell:
    creates: "{{ miniforge_home }}/bin/mamba"
    cmd: |
      /tmp/miniforge.sh -b -p "{{ miniforge_home }}"
  when: not stat_conda.stat.exists

- name: Ensure conda.sh activated in shell
  become: true
  ansible.builtin.file:
    src: "{{ miniforge_home }}/etc/profile.d/conda.sh"
    dest: /etc/profile.d/conda.sh
    state: link

- name: Ensure conda activate directory exists
  become: true
  ansible.builtin.file:
    path: "{{ miniforge_home }}/etc/conda/activate.d"
    state: directory
    mode: "0755"

- name: Create conda configuration directory
  become: true
  ansible.builtin.file:
    path: /etc/conda
    state: directory

- name: Remove implicit .condarc file installed by miniforge
  become: true
  ansible.builtin.file:
    path: "{{ miniforge_home }}/.condarc"
    state: absent

- name: Create default condarc for users
  become: true
  ansible.builtin.copy:
    dest: /etc/conda/condarc
    mode: 644
    content: |
      channels:
        - conda-forge
      envs_dirs:
      {% for directory in miniforge_envs %}
        - "{{ directory }}"
      {% endfor %}
