mysql_enabled: false
mysql_databases:
  - slurm
  - conda-store

mysql_users:
  - username: slurm
    password: W9T0N4ejQBR4RmQCU6GmbbZa
    privileges: '*.*:ALL'
  - username: conda-store
    password: eIbmUditL4RbQm0YPeLozRme
    privileges: '*.*:ALL'
