---
mysql_enabled: false
mysql_config_file: /etc/mysql/my.cnf

mysql_databases:
  - slurm
  - conda-store

mysql_config:
  max_connections: 200

mysql_users:
  - username: slurm
    password: W9T0N4ejQBR4RmQCU6GmbbZa
    privileges: "*.*:ALL"
  - username: conda-store
    password: eIbmUditL4RbQm0YPeLozRme
    privileges: "*.*:ALL"

# Define a custom list of packages to install
mysql_packages:
  - mysql-server
  - mysql-common

mysql_python_package: python3-mysqldb
