# handlers file for ansible-role-ldap
---
- name: Restart services ldap
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: "yes"
    state: restarted
  with_items:
    - nscd
    - nslcd
