---
 - name: Install jupyterhub server
   include_tasks: jupyterhub.yaml
   when: jupyterhub_enabled

 - name: Install jupyterhub_ssh server
   include_tasks: jupyterhub_ssh.yaml
   when: jupyterhub_ssh_enabled
