---
 - name: Ensure slurm state directory exists
   become: true
   file:
     path: "{{ slurm.config.StateSaveLocation }}"
     state: directory
     mode: '0700'
     owner: slurm
     group: slurm

 - name: Ensure slurm log directory exists
   become: true
   file:
     path: "{{ slurm.config.SlurmctldLogFile | dirname }}"
     state: directory
     mode: '0700'
     owner: slurm
     group: slurm

 - name: Ensure slurm pid directory exists
   become: true
   file:
     path: "{{ slurm.config.SlurmctldPidFile | dirname }}"
     state: directory
     mode: '0755'
     owner: slurm
     group: slurm

 - name: Copy the slurmctl systemd service file
   become: true
   copy:
     content: |
       [Unit]
       Description=Slrum controller daemon
       After=network.target munge.service
       ConditionPathExists=/etc/slurm-llnl/slurm.conf

       [Service]
       Type=forking
       User=slurm
       ExecStart=/usr/sbin/slurmctld
       ExecReload=/bin/kill -HUN $MAINPID
       PIDFile={{ slurm.config.SlurmctldPidFile }}
       LimitNOFILE=65536
       TasksMax=infinity

       [Install]
       WantedBy=multi-user.target
     dest: /etc/systemd/system/slurmctld.service
     owner: root
     group: root
     mode: 0644
   register: _slurmctld_service

 - name: Install slurm controller packages
   become: true
   apt:
     state: latest
     cache_valid_time: 3600
     name:
       - slurmctld
   register: _slurmctld_package

 - name: Ensure slurmctld is enabled on boot
   become: true
   systemd:
     daemon_reload: true
     name: slurmctld
     enabled: true
     state: restarted
   when: _slurm_config.changed or _slurm_cgroup_config.changed or _slurmctld_service.changed or _slurmctld_package.changed
