---
- name: Restart services jupyterhub
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: "yes"
    state: restarted
  with_items:
    - jupyterhub

- name: Restart services jupyterhub-proxy
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: "yes"
    state: restarted
  with_items:
    - jupyterhub-proxy

- name: Restart services jupyterhub-ssh
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: "yes"
    state: restarted
  with_items:
    - jupyterhub-ssh
