---
 - name: "restart services jupyterhub"
   become: true
   service:
     name={{item}}
     enabled=yes
     state=restarted
   with_items:
     - "jupyterhub"

 - name: "restart services jupyterhub-proxy"
   become: true
   service:
     name={{item}}
     enabled=yes
     state=restarted
   with_items:
     - "jupyterhub-proxy"

 - name: "restart services jupyterhub-ssh"
   become: true
   service:
     name={{item}}
     enabled=yes
     state=restarted
   with_items:
     - "jupyterhub-ssh"
