---
- name: Install munge
  ansible.builtin.include_tasks: munge.yaml
  when: munge_enabled

- name: Install slurm client packages
  become: true
  timeout: 300
  ansible.builtin.apt:
    state: latest
    cache_valid_time: 3600
    name:
      - slurm-client
      - slurm-wlm-doc

- name: Ensure that slurm configuration directory exists
  become: true
  ansible.builtin.file:
    path: "{{ SlurmConfigFileDIr }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Install slurm.conf
  become: true
  ansible.builtin.template:
    src: templates/slurm.conf
    dest: "{{ SlurmConfigFileDIr }}/slurm.conf"
    owner: root
    group: root
    mode: "0755"
  register: _slurm_config

- name: Install extra execution host configs
  become: true
  ansible.builtin.copy:
    content: |
      CgroupAutomount=yes
      ConstrainCores=yes
      ConstrainRAMSpace=yes
      ConstrainSwapSpace=yes
    dest: "{{ SlurmConfigFileDIr }}/cgroup.conf"
    owner: root
    group: root
    mode: "0444"
  register: _slurm_cgroup_config

- name: Install slurmdbd
  ansible.builtin.include_tasks: slurmdbd.yaml
  when: slurmdbd_enabled

- name: Install slurmctld
  ansible.builtin.include_tasks: slurmctld.yaml
  when: slurmctld_enabled

- name: Install slurmd
  ansible.builtin.include_tasks: slurmd.yaml
  when: slurmd_enabled

- name: Install slurm exporter
  ansible.builtin.include_tasks: slurm_exporter.yaml
  when: slurm_exporter_enabled
