---
# Must be writable by user SlurmUser.
- name: Ensure slurmdbd log directory exists
  become: true
  ansible.builtin.file:
    path: "{{ slurmdbd_config.LogFile | dirname }}"
    state: directory
    mode: "0755"
    owner: slurm
    group: slurm

# Must be writable by user SlurmUser.
- name: Ensure slurm pid directory exists
  become: true
  ansible.builtin.file:
    path: "{{ slurmdbd_config.PidFile | dirname }}"
    state: directory
    mode: "0755"
    owner: slurm
    group: slurm

# This file should be only on the computer where SlurmDBD executes
# and should only be readable by the user which executes SlurmDBD (e.g. "slurm").
# This file should be protected from unauthorized access since
# it contains a database password
- name: Install slurmdbd.conf
  become: true
  ansible.builtin.template:
    src: templates/slurmdbd.conf
    dest: "{{ SlurmConfigFileDIr }}/slurmdbd.conf"
    owner: slurm
    group: slurm
    mode: "0600"
  register: _slurmdbd_config

- name: Copy the slurmdbd systemd service file
  become: true
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Slurm DBD accounting daemon
      After=network.target munge.service
      ConditionPathExists={{ SlurmConfigFileDIr }}/slurmdbd.conf

      [Service]
      Type=forking
      User=slurm
      ExecStart=/usr/sbin/slurmdbd
      ExecReload=/bin/kill -HUN $MAINPID
      PIDFile={{ slurmdbd_config.PidFile }}
      LimitNOFILE=65536
      TasksMax=infinity

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/slurmdbd.service
    owner: root
    group: root
    mode: "0644"
  register: _slurmdbd_service

- name: Install slurm controller packages
  become: true
  timeout: 300
  ansible.builtin.apt:
    state: latest
    cache_valid_time: 3600
    name:
      - slurmdbd
  register: _slurmdbd_package

- name: Ensure slurmdbd is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: slurmdbd
    enabled: true
    state: restarted
  when: _slurmdbd_config.changed or _slurmdbd_service.changed or _slurmdbd_package.changed
