---
- name: Install golang
  ansible.builtin.include_tasks: golang.yaml

- name: Check that the slurm exporter binary exists
  ansible.builtin.stat:
    path: /usr/local/bin/prometheus_slurm_exporter
  register: _slurm_exporter_stat

- name: Download prometheus-slurm-exporter tarball to local folder
  ansible.builtin.get_url:
    url: https://github.com/vpenso/prometheus-slurm-exporter/archive/{{ slurm_exporter_version }}.tar.gz
    checksum: sha256:{{ slurm_exporter_sha256 }}
    dest: /tmp/prometheus-slurm-exporter-{{ slurm_exporter_version }}.tar.gz
    force: false
    mode: "0755"
  when: not _slurm_exporter_stat.stat.exists

- name: Unpack prometheus slurm exporter
  ansible.builtin.unarchive:
    src: /tmp/prometheus-slurm-exporter-{{ slurm_exporter_version }}.tar.gz
    remote_src: true
    dest: /tmp
    creates: /tmp/prometheus-slurm-exporter-{{ slurm_exporter_version }}/main.go
  when: not _slurm_exporter_stat.stat.exists

- name: Build prometheus_slurm_exporter
  ansible.builtin.shell:
    chdir: /tmp/prometheus-slurm-exporter-{{ slurm_exporter_version }}/
    cmd: |
      export GOPATH=/tmp/
      /opt/go/bin/go mod download
      /opt/go/bin/go build -o bin/prometheus_slurm_exporter main.go accounts.go cpus.go nodes.go partitions.go queue.go scheduler.go users.go
    creates: /tmp/prometheus-slurm-exporter-{{ slurm_exporter_version }}/bin/prometheus_slurm_exporter
  when: not _slurm_exporter_stat.stat.exists

- name: Install prometheus_slurm_exporter binary
  become: true
  ansible.builtin.copy:
    src: /tmp/prometheus-slurm-exporter-{{ slurm_exporter_version }}/bin/prometheus_slurm_exporter
    dest: /usr/local/bin/prometheus_slurm_exporter
    remote_src: true
    mode: "0755"
    owner: root
    group: root
  when: not _slurm_exporter_stat.stat.exists

- name: Create prometheus_slurm_exporter group
  become: true
  ansible.builtin.group:
    name: prometheus_slurm_exporter
    state: present
    system: true

- name: Create the prometheus_slurm_exporter user
  become: true
  ansible.builtin.user:
    name: prometheus_slurm_exporter
    groups: prometheus_slurm_exporter
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /

- name: Copy the prometheus_slurm_exporter systemd service file
  become: true
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Prometheus SLURM Exporter

      [Service]
      User=prometheus_slurm_exporter
      Group=prometheus_slurm_exporter
      ExecStart=/usr/local/bin/prometheus_slurm_exporter -listen-address :{{ slurm_exporter_port }}
      Restart=always
      RestartSec=15

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus_slurm_exporter.service
    owner: root
    group: root
    mode: "0644"
  register: _slurm_exporter_service

- name: Ensure prometheus_slurm_exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus_slurm_exporter
    enabled: true
    state: restarted
  when: _slurm_exporter_service.changed
