
HPC01_TEST = "hpc01-test" + (ENV['HPC_VM_PREFIX'] || '')
HPC02_TEST = "hpc02-test" + (ENV['HPC_VM_PREFIX'] || '')
HPC03_TEST = "hpc03-test" + (ENV['HPC_VM_PREFIX'] || '')


Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  # forces to use $HOME/.vagrant.d/insecure_private_key' we need the
  # ssh key to be the same when /home get mounted on nfs
  config.ssh.insert_key = false

  config.vm.define HPC01_TEST, primary: true do |hpc01|
    hpc01.vm.hostname = HPC01_TEST
    hpc01.vm.provider "libvirt" do |libvirthpc01|
      libvirthpc01.memory = 6144
      libvirthpc01.cpus = 2
    end

    hpc01.vm.provider "virtualbox" do |vboxhpc01|
      vboxhpc01.memory = 6144
      vboxhpc01.cpus = 2
      vboxhpc01.gui = true
    end
  end

  config.vm.define HPC02_TEST do |hpc02|
    hpc02.vm.hostname = HPC02_TEST
    hpc02.vm.provider "libvirt" do |libvirthpc02|
      libvirthpc02.memory = 6144
      libvirthpc02.cpus = 4
    end

    hpc02.vm.provider "virtualbox" do |vboxhpc02|
      vboxhpc02.memory = 6144
      vboxhpc02.cpus = 4
      vboxhpc02.gui = true
    end
  end

  config.vm.define HPC03_TEST do |hpc03|
    hpc03.vm.hostname = HPC03_TEST
    hpc03.vm.provider "libvirt" do |libvirthpc03|
      libvirthpc03.memory = 6144
      libvirthpc03.cpus = 4
    end

    hpc03.vm.provider "virtualbox" do |vboxhpc03|
      vboxhpc03.memory = 6144
      vboxhpc03.cpus = 4
      vboxhpc03.gui = true
    end
  end

  # issues with dnssec and https://github.com/lavabit/robox/issues/106
  config.vm.provision 'shell', inline: "if grep 'DNSSEC=yes' /etc/systemd/resolved.conf; then sed -i 's/DNSSEC=yes/DNSSEC=no/g' /etc/systemd/resolved.conf; systemctl restart systemd-resolved.service; fi", privileged: true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../playbook.yaml"
    ansible.groups = {
      "hpc-master" => [HPC01_TEST],
      "hpc-worker" => [HPC02_TEST, HPC03_TEST],
      "partition-example" => [HPC03_TEST],
    }
    ansible.raw_arguments = [
      "-f 5",  # number of hosts to configure in parallel
    ]
    ansible.extra_vars = {
      nfs_client: {
        mounts: [
          { path: '/home' ,
            host: HPC01_TEST },
          { path: '/opt/conda' ,
            host: HPC01_TEST }
        ]
      }
    }
  end
end
