---
- name: Install Dask Gateway
  ansible.builtin.include_role:
    name: conda_environment
  vars:
    environment_path: "{{ dask_gateway_environment }}"

- name: Create dask group
  become: true
  ansible.builtin.group:
    name: dask
    state: present
    system: true

- name: Create the dask user
  become: true
  ansible.builtin.user:
    name: dask
    groups: dask
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /

- name: Ensure that dask-gateway configuration directory exists
  become: true
  ansible.builtin.file:
    path: /etc/dask-gateway
    state: directory
    mode: "0700"
    owner: dask
    group: dask

- name: Ensure that dask-gateway runtime directory exists
  become: true
  ansible.builtin.file:
    path: /var/lib/dask-gateway
    state: directory
    mode: "0700"
    owner: dask
    group: dask

- name: Copy the dask-gateway configuration
  become: true
  ansible.builtin.template:
    src: templates/dask_gateway_config.py
    dest: /etc/dask-gateway/dask_gateway_config.py
    owner: dask
    group: dask
    mode: "0644"
  notify: Restart services dask-gateway

- name: Copy the dask-gateway systemd service file
  become: true
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=dask-gateway
      After=network-online.target

      [Service]
      Type=simple
      User=root
      Group=root
      # By default, $PATH is pretty bare (thanks, systemd)
      # We add the conda dir & /bin
      # batchspawner uses sudo, which is in /bin (at least on CentOS)
      Environment=PATH={{ miniforge_home }}/condabin:{{ miniforge_home }}/envs/{{ dask_gateway_environment | basename | splitext | first }}/bin:$PATH:/bin:/usr/bin:/usr/local/bin
      ExecStart={{ miniforge_home }}/envs/{{ dask_gateway_environment | basename | splitext | first }}/bin/dask-gateway-server -f /etc/dask-gateway/dask_gateway_config.py
      Restart=always
      WorkingDirectory=/var/lib/dask-gateway

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/dask-gateway.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart services dask-gateway

- name: Ensure dask-gateway is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: dask-gateway
    enabled: true
    state: started
