---
traefik_enabled: false
traefik_version: 2.4.0
traefik_sha256: 1e8cd14a0c09ba44ba8b44a94441caaf1edc3e043a65a7d43f9c870be47f70aa
traefik_metrics_port: "8082"

traefik_tls_type: self-signed
# traefik_domain: <dns-name>
# traefik_letsencrypt_email: <email> # required if type == "letsencrypt"
# traefik_tls_certificate: <local-path>
# traefik_tls_key: <local-path>

# role: jupyterhub
jupyterhub_proxy_port: "15002"
jupyterhub_base_url: /
jupyterhub_ssh_internal_port: "8021"
jupyterhub_ssh_external_port: "8022"

# role: grafana
grafana_port: "3000"
grafana_base_url: /monitoring

# role: dask_gateway
dask_gateway_api_port: "8010"
dask_gateway_scheduler_internal_port: "8785"
dask_gateway_scheduler_external_port: "8786"

# role: keycloak
keycloak_port: "30020"

# role: conda_store
conda_store_prefix: /conda-store
conda_store_port: "5000"

# role: minio
minio_internal_port: "9001"
minio_external_port: "9080"
