{
 "title": "JupyterHub",
 "description": "IDR JupyterHub",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Jupyter servers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"jupyter-.*\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Jupyter CPU (user)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (irate(container_cpu_user_seconds_total{namespace=~\"jupyterhub-.*\"}[5m])) * 100",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Jupyter Memory (RSS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (container_memory_rss{namespace=~\"jupyterhub-.*\"})",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}