---
- name: Ensure apt packages are installed
  become: true
  timeout: 300
  ansible.builtin.apt:
    name: "{{ installed_packages }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
