name: jupyterhub
channels:
  - conda-forge
dependencies:
  - pip==21.1.2
  - jupyterhub{{ jupyterhub_version }}
  - jupyterhub-kubespawner==4.2.0
  - oauthenticator==15.1.0
  - escapism==1.0.1
  - jupyterhub-idle-culler==1.2.1
  - sqlalchemy==1.4.46
  - batchspawner==1.3.0
  - pip:
      - nebari_jupyterhub_theme==2023.4.1
      - python-keycloak==0.26.1
      - jupyterhub-traefik-proxy==1.1.0
      # jupyterhub-ssh has not made a release yet
      - git+https://github.com/yuvipanda/jupyterhub-ssh.git
      - jhub-apps==2024.2.1rc1
