name: jupyterlab
channels:
  - conda-forge
dependencies:
# general
  - pip
  # jupyterhub/jupyterlab
  - nb_conda_kernels
  - ipython > 7
  - jupyter-server-proxy
  - jupyter_server==1.17.1
  - jupyterlab==3.4.0
  - jupyter_client
  - jupyter_console
  - jupyterhub==2.3.0
  - nbconvert
  - nbval
  - retrolab

  # jupyterlab extensions
  - dask_labextension >= 5.3.0
  - jupyterlab-git >=0.30.0
  - sidecar >=0.5.0
  - ipywidgets ==7.7.1
  - ipyleaflet >=0.13.5
  - pyviz_comms >=2.0.1
  - jupyter-resource-usage >=0.6.0
  - nbgitpuller
  - jupyterlab_code_formatter

  # cds dashboards
  - cdsdashboards-singleuser==0.6.3
  - jhsingle-native-proxy==0.8.0

  # viz tools
  - param
  - python-graphviz
  - plotly >=5.0

  # testing, docs, linting
  - pytest
  - hypothesis
  - flake8
  - sphinx
  - pytest-cov
  - black
  - isort
  - importnb

  - pip:
      # vscode jupyterlab launcher
      - git+https://github.com/betatim/vscode-binder
