name: jupyterlab
channels:
  - conda-forge
dependencies:
  - pip
  - nb_conda_kernels
  # required to launch jupterlab from jupyterhub
  - jupyterhub>=1.3.0
  # jupyterhub menu https://github.com/jupyterlab/jupyterlab/issues/9428
  - jupyterlab>=3.0.4
  - ipywidgets>=7.6.0
  - ipyparallel
  # vscode
  - code-server >= 3.2
  # dask
  - dask-gateway
  - dask-labextension>=5.0.0
  - pip:
      # vscode jupyterlab launcher
      - git+https://github.com/betatim/vscode-binder
      # batchspawner latest slurm fixes
      - https://github.com/jupyterhub/batchspawner/archive/129951ad11e3049567b94adb8c9725dc22225a1a.tar.gz
