name: jupyterhub
channels:
  - conda-forge
dependencies:
  - pip
  - jupyterhub{{ jupyterhub_version }}
  - oauthenticator
  - jupyterhub-idle-culler
  - jupyterhub-systemdspawner
  - python-keycloak
  - pip:
      - qhub-jupyterhub-theme==0.3.1
      - jupyterhub-traefik-proxy
      # jupyterhub-ssh has not made a release yet
      - git+https://github.com/yuvipanda/jupyterhub-ssh.git
      - batchspawner==1.1.0
      # cdsdashboards
      - cdsdashboards==0.5.0b2
