name: jupyterhub
channels:
  - conda-forge
dependencies:
  - pip==21.1.2
  - jupyterhub==2.3.0
  - jupyterhub-kubespawner==1.1.0
  - oauthenticator==14.1.0
  - escapism==1.0.1
  - cdsdashboards==0.6.3
  - jupyterhub-idle-culler==1.0
  - pip:
      - qhub-jupyterhub-theme==0.3.6
      - sqlalchemy==1.4.4
      - python-keycloak==0.26.1
      - jupyterhub-traefik-proxy==0.3.0
      - batchspawner==1.1.0
      # jupyterhub-ssh has not made a release yet
      - git+https://github.com/yuvipanda/jupyterhub-ssh.git
