name: jupyterhub
channels:
  - conda-forge
dependencies:
  - pip
  - jupyterhub>=1.3.0
  - oauthenticator
  - jupyterhub-idle-culler
  - jupyterhub-systemdspawner
  - pip:
      - qhub-jupyterhub-theme==0.3.1
      - jupyterhub-traefik-proxy
      # jupyterhub-ssh has not made a release yet
      - git+https://github.com/yuvipanda/jupyterhub-ssh.git
      # batchspawner latest slurm fixes
      - https://github.com/jupyterhub/batchspawner/archive/129951ad11e3049567b94adb8c9725dc22225a1a.tar.gz
      # cdsdashboards
      - cdsdashboards==0.5.0b2
