name: jupyterlab
channels:
  - conda-forge
dependencies:
  - pip
  - nb_conda_kernels
  # required to launch jupterlab from jupyterhub
  - jupyterhub>=1.3.0
  # jupyterhub menu https://github.com/jupyterlab/jupyterlab/issues/9428
  - jupyterlab>=3.0.4
  - ipywidgets>=7.6.0
  - ipyparallel
  # vscode
  - code-server >= 3.2
  # dask
  - dask-gateway
  - dask-labextension>=5.0.0
  - pip:
      # conda-store (mamba-org/gator)
      - https://github.com/mamba-org/gator/archive/conda-store-integration.tar.gz
      # vscode jupyterlab launcher
      - git+https://github.com/betatim/vscode-binder
      - batchspawner==1.1.0
