---
- name: Install nfs
  become: true
  ansible.builtin.apt:
    state: latest
    cache_valid_time: 3600
    name:
      - nfs-common

- name: Wait for nfs server at host to be available
  ansible.builtin.wait_for:
    host: "{{ item.host }}"
    port: 2049
    timeout: 600
  with_items: "{{ nfs_client_mounts }}"

- name: Ensure nfs mounted directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ nfs_client_mounts }}"

- name: Add fstab entries for nfs mounts
  become: true
  ansible.posix.mount:
    src: "{{ item.host }}:{{ item.path }}"
    path: "{{ item.path }}"
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs
  with_items: "{{ nfs_client_mounts }}"
