---
- name: Install nfs server
  ansible.builtin.include_tasks: server.yaml
  when: nfs_server_enabled

- name: Install nfs client
  ansible.builtin.include_tasks: client.yaml
  when: nfs_client_enabled
