---
- name: Create environments directory
  become: true
  ansible.builtin.file:
    path: /opt/conda-environments
    state: directory

- name: Copy environments files
  become: true
  ansible.builtin.template:
    src: "{{ environment_path }}"
    dest: /opt/conda-environments/{{ environment_path | basename }}
    mode: "0644"
  register: _environment

- name: Install conda environment {{ environment_path | basename }}
  become: true
  ansible.builtin.command:
    cmd: "{{ miniforge_home }}/bin/mamba env update -f /opt/conda-environments/{{ environment_path | basename }} --prefix {{ miniforge_home }}/envs/{{ environment_path
      | basename | splitext | first }}"
  when: _environment.changed
