jupyterhub_ssh_enabled: false
jupyterhub_ssh_internal_port: "8021"
jupyterhub_ssh_external_port: "8022"

jupyterhub_proxy_port: "15002"
jupyterhub_proxy_api_port: "15003"
jupyterhub_proxy_auth_token: "m8dfdKvyVJ0bWTNpbVCQyoCt"

cdsdashboards_enabled: true

jupyterhub_enabled: false
jupyterhub_version: "==4.0.2"
jupyterhub_port: "15001"
jupyterhub_base_url: "/"
jupyterhub_hub_environment: "environments/jupyterhub.yaml"
jupyterhub_lab_environment: "environments/jupyterlab.yaml"
jupyterhub_dashboard_environment: "environments/dashboards.yaml"
jupyterhub_client_id: "jupyterhub"
jupyterhub_client_secret: "SUPERSECRETPASSWORDJUPYTERHUB"
jupyterhub_qhub_options_form: true

jupyterhub_config:
  spawner:
    start_timeout: 180 # seconds

jupyterhub_services:
  dask_gateway:
    CStgn1NN8DogQR1KajuoQfye1qNRqx6zsh

    # hub_title: str = "Nebari"
    # hub_subtitle: str = "Your open source data science platform"
    # welcome: str = """Welcome! Learn about Nebari's features and configurations in <a href="https://www.nebari.dev/docs">the documentation</a>. If you have any questions or feedback, reach the team on <a href="https://www.nebari.dev/docs/community#getting-support">Nebari's support forums</a>."""
    # logo: str = "https://raw.githubusercontent.com/nebari-dev/nebari-design/main/logo-mark/horizontal/Nebari-Logo-Horizontal-Lockup-White-text.svg"
    # primary_color: str = "#4f4173"
    # primary_color_dark: str = "#4f4173"
    # secondary_color: str = "#957da6"
    # secondary_color_dark: str = "#957da6"
    # accent_color: str = "#32C574"
    # accent_color_dark: str = "#32C574"
    # text_color: str = "#111111"
    # h1_color: str = "#652e8e"
    # h2_color: str = "#652e8e"
    # version: str = f"v{__version__}"
    # navbar_color: str = "#1c1d26"
    # navbar_text_color: str = "#f1f1f6"
    # navbar_hover_color: str = "#db96f3"

jupyterhub_theme:
  template_vars:
    hub_title: "This is QHub HPC"
    hub_subtitle: "Your scalable open source data science laboratory."
    welcome: "have fun."
    logo: "https://www.smsu.edu/_files/images/svg/southwest-minnesota-state-university-white-gold-logo.svg"
    primary_color: "#3a1807"
    secondary_color: "#3a1807"
    accent_color: "#bcaa71"
    text_color: "#111111"
    h1_color: "#612e10"
    h2_color: "#612e10"
    navbar_hover_color: "#3a1807"

# for each key
#    c.{classname}.{attribute} = {value}
jupyterhub_custom: {}

# "name": "<local-path>"
# use variable: inventory_dir to point to use inventory directory
jupyterhub_additional_config: {}

idle_culler:
  enabled: true
  timeout: 86400 # 1 day
  cull_every: 3600 # 1 hour

# role: miniforge
miniforge_home: "/opt/conda"

# role: traefik
# traefik_domain: ...

# role: keycloak
keycloak_port: "30020"
keycloak_admin_username: "admin"
keycloak_admin_password: XLWUMUu8OG0XqlMREZK9id9o
keycloak_realm: qhub-hpc
