---
 - name: Check that the node exporter binary exists
   stat:
     path: "/usr/local/bin/node_exporter"
   register: _node_exporter_stat

 - name: Download node_exporter binary to local folder
   get_url:
     url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
     checksum: "sha256:{{ node_exporter_sha256 }}"
     dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
     force: false
     mode: 0755
   when: not _node_exporter_stat.stat.exists

 - name: Unpack node_exporter binary
   unarchive:
     src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
     remote_src: true
     dest: "/tmp"
     creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
   when: not _node_exporter_stat.stat.exists

 - name: Install node_exporter binary
   become: true
   copy:
     src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
     dest: "/usr/local/bin/node_exporter"
     remote_src: true
     mode: 0755
     owner: root
     group: root
   when: not _node_exporter_stat.stat.exists

 - name: Create node_exporter group
   become: true
   group:
    name: node_exporter
    state: present
    system: true

 - name: Create the node_exporter user
   become: true
   user:
     name: node_exporter
     groups: node_exporter
     append: true
     shell: /usr/sbin/nologin
     system: true
     create_home: false
     home: /

 - name: Copy the node_exporter systemd service file
   become: true
   copy:
     content: |
       [Unit]
       Description=Prometheus Node Exporter
       After=network-online.target

       [Service]
       Type=simple
       User=node_exporter
       Group=node_exporter
       ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}
       SyslogIdentifier=node_exporter
       Restart=always
       RestartSec=1
       StartLimitInterval=0
       ProtectSystem=strict
       ProtectControlGroups=true
       ProtectKernelModules=true
       ProtectKernelTunables=yes

       [Install]
       WantedBy=multi-user.target
     dest: /etc/systemd/system/node_exporter.service
     owner: root
     group: root
     mode: 0644
   register: _node_exporter_service

 - name: Ensure Node Exporter is enabled on boot
   become: true
   systemd:
     daemon_reload: true
     name: node_exporter
     enabled: true
     state: started
   when: _node_exporter_service.changed
