Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"

  # forces to use $HOME/.vagrant.d/insecure_private_key' we need the
  # ssh key to be the same when /home get mounted on nfs
  config.ssh.insert_key = false

  config.vm.define "hpc01-test", primary: true do |hpc01|
    hpc01.vm.hostname = "hpc01-test"
    hpc01.vm.provider "libvirt" do |libvirthpc01|
      libvirthpc01.memory = 4096
      libvirthpc01.cpus = 2
    end

    hpc01.vm.provider "virtualbox" do |vboxhpc02|
      vboxhpc01.memory = 4096
      vboxhpc01.cpus = 2
      vboxhpc01.gui = true
    end
  end

  config.vm.define "hpc02-test" do |hpc02|
    hpc02.vm.hostname = "hpc02-test"
    hpc02.vm.provider "libvirt" do |libvirthpc02|
      libvirthpc02.memory = 8192
      libvirthpc02.cpus = 4
    end

    hpc02.vm.provider "virtualbox" do |vboxhpc02|
      vboxhpc02.memory = 8192
      vboxhpc02.cpus = 4
      vboxhpc02.gui = true
    end
  end

  config.vm.define "hpc03-test" do |hpc03|
    hpc03.vm.hostname = "hpc03-test"
    hpc03.vm.provider "libvirt" do |libvirthpc03|
      libvirthpc03.memory = 8192
      libvirthpc03.cpus = 4
    end

    hpc03.vm.provider "virtualbox" do |vboxhpc03|
      vboxhpc03.memory = 8192
      vboxhpc03.cpus = 4
      vboxhpc03.gui = true
    end
  end

  # issues with dnssec and https://github.com/lavabit/robox/issues/106
  config.vm.provision 'shell', inline: "if grep 'DNSSEC=yes' /etc/systemd/resolved.conf; then sed -i 's/DNSSEC=yes/DNSSEC=no/g' /etc/systemd/resolved.conf; systemctl restart systemd-resolved.service; fi", privileged: true


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../playbook.yaml"
    ansible.groups = {
      "hpc-master" => ["hpc01-test"],
      "hpc-worker" => ["hpc02-test", "hpc03-test"],
      "partition-example" => ["hpc03-test"],
    }
    ansible.raw_arguments = [
      "-f 5",  # number of hosts to configure in parallel
    ]
  end
end
