---
postgres_enabled: false
postgres_databases:
  - conda-store
pg_data_directory: /opt/conda-store/postgres/data/
pg_user: conda-store
pg_version: 14

postgres_users:
  - username: conda-store
    password: eIbmUditL4RbQm0YPeLozRme
    role: CREATEDB,CREATEROLE
