name: "Vagrant (KVM) Tests"

on:
  pull_request:
  push:
    branches:
      - "*"

jobs:
  # https://github.com/jonashackt/vagrant-github-actions
  test-kvm:
    name: "KVM Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Install test dependencies.
        run: sudo pip3 install ansible

      - name: Install Ansible Dependencies
        working-directory: tests/ubuntu2004-singlenode
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install ansible.posix

      - name: Vagrant Install
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vagrant

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        working-directory: tests/ubuntu2004-singlenode
        run: vagrant up
