---
name: Vagrant (KVM) Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # https://github.com/jonashackt/vagrant-github-actions
  test-kvm:
    name: KVM Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install ansible

      - name: Install Ansible dependencies
        run: |
          ansible-galaxy collection install -r requirements.yaml

      - name: Create deploy folder and move inventory files
        run: |
          mkdir deploy
          cp -r inventory.template/* deploy/
          cp .github/workflows/inventory.ini deploy/inventory.ini

      - name: Update firwall_internal_ip_range
        run: |
          echo "firewall_internal_ip_range: $(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)" >> deploy/group_vars/all.yaml

      - name: Run ansible playbook
        run: |
          cd deploy
          ansible-playbook ../playbook.yaml -i inventory.ini --connection=local -v
        env:
          ANSIBLE_FORCE_COLOR: True
