---
name: Ansible Lint

on:
  push:
    paths:
      - 'roles/**'
      - 'tasks/**'
      - '.github/workflows/ansible-lint.yml'

  pull_request:
    paths:
      - 'roles/**'
      - 'tasks/**'
      - '.github/workflows/ansible-lint.yml'

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
