---
name: Ansible Lint

on:
  push:
  pull_request:
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.9.2

      - name: Check ansible-lint diff
        if: failure()
        uses: ansible/ansible-lint@v24.9.2
        with:
          args: --fix

      - name: Check ansible lint diff and undo
        if: failure()
        run: |
          git diff
