---
- name: Install samba server
  ansible.builtin.include_tasks: server.yaml
  when: samba_server_enabled

- name: Install samba client
  ansible.builtin.include_tasks: client.yaml
  when: samba_client_enabled
